### ISSUE TITLE
Bugs in iOS9 Safari

### ISSUE THREAD

**Issue by ghost** [sarahdayan/feedify#1]
I don't know if this also happens in other mobile browsers, but in Safari on iOS9, the headers don't update until the current swipe's momentum scroll is finished.

**Comment by sarahdayan** [comment]
Hello, this is the intended effect :) The plugin replicates Instagram's "stick to top then drop" effect with the header. The header remains fixed at the top of the page until its associated item is done scrolling. Then it's "pushed" by the following.

**Comment by ghost** [comment]
I think maybe I didn't explain myself very well, so I made a [video](https://youtu.be/hZnuzQCHavs) of the issue on your demo page. When you scroll to a new `.feedify-item`, the `.feedify-item-header` doesn't stick to the top of the page until you lift your finger from the touchscreen.

In my own project, the issue looks like [this](https://youtu.be/ZUYcydoYx2E). I think the issue has to do with when iOS updates `scrollTop()` - it doesn't happen continuously, but only when you lift your finger. A possible workaround would be to use [iScroll](http://iscrolljs.com), maybe?

**Comment by sarahdayan** [comment]
You were right, there was a problem indeed. It wasn't linked to scrolling events but to hardware performance limitation that made the sticky header disappear on position change while scrolling. Fixed with a CSS workaround.
