### ISSUE TITLE
Offsets - triggering switch

### ISSUE THREAD

**Issue by sp00ne** [sarahdayan/feedify#2]
Hi there!

Great plugin! Love that it doesn't flicker on scroll for mobile devices.
There is one "bug" or perhaps a misunderstanding from my side.

I have a `<div>` above the feedify-item-headers - and it seems that the switch triggers when the next header to get "stuck" hits the viewport height = 0. It should trigger the switch where the previous header is located position-wise, am I right?

**Comment by sp00ne** [comment]
#3 - Issue is fixed in my pull request

**Comment by sarahdayan** [comment]
Hey! Version 1.2.0 solves this issue. Thanks for your suggestion :)

**Comment by sp00ne** [comment]
Ah although I don't mind so much, your action basically nullified my contribution to your code :(
